# -*- coding: utf-8 -*-
"""Election Data - R-Studio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BT1OP4zB868PgoABnxIPK00zDK1heCxs

# Housekeeping

## Imports
"""

library(dplyr)
library (tidyr)
library(ggplot2)

#drive_auth()

election_df <- read.csv ('https://drive.google.com/uc?export=download&id=1iPZ6CJ6GI3mzTk4AOjLpw7xQi2pge326')
county_df <- read.csv('https://drive.google.com/uc?export=download&id=1xwSW0hlo_tVFwk6sFMoKr6_kKOrfgfOo')

head(election_df)

head(county_df)

#merge datasets by fips
df <- merge(election_df, county_df, by="fips")

head(df)

"""## Cleaning"""

names(df)

#renaming columns

df <- df %>%
  rename(
    "Population_2014_estimate" = "PST045214",
    "Population_2010_estimate" ="PST040210",
    "Population_2010_pct_change"="PST120214",
    "Population_2010" ="POP010210",
    "Under_5_pct_2014" = "AGE135214",
    "Under_18_pct_2014" = "AGE295214",
    "Above_65_pct_2014" = "AGE775214",
    "Female_pct_2014" = "SEX255214",
    "White_pct_2014" = "RHI125214",
    "African_American_pct_2014" = "RHI225214",
    "Native_American_pct_2014" = "RHI325214",
    "Asian_pct_2014" = "RHI425214",
    "Pacific_Islander_pct_2014" = "RHI525214",
    "Two_or_More_Races_pct_2014" = "RHI625214",
    "Hispanic_pct_2014" = "RHI725214",
    "White_non_Hispanic_pct_2014" = "RHI825214",
    "Living_same_house_1_year" = "POP715213",
    "Foreign_Born_pct_2013" = "POP645213",
    "Language_Other_than_English_pct_2009_2013" = "POP815213",
    "High_School_Grad_pct_2009_2013"= "EDU635213",
    "Bachelors_Degree_pct_2009_2013" = "EDU685213",
    "Veterans_2009_2013" = "VET605213",
    "Mean_Travel_Time_to_Work_2009_2013" = "LFE305213",
    "Housing_Units_2014" = "HSG010214",
    "Homeownership_Rate_2009_2013" = "HSG445213",
    "Housing_Units_Multi_Unit_2009_2013" = "HSG096213",
    "Housing_Median_Value_2013" = "HSG495213",
    "Households_2009_2013" = "HSD410213",
    "Persons_Households_2009_2013" = "HSD310213",
    "Income_Per_Capita_2009_2013" = "INC910213",
    "Median_Household_Income_2009_2013" = "INC110213",
    "Persons_Below_Poverty_pct_2009_2013" = "PVY020213",
    "Private_Nonfarm_Establishments_2013" = "BZA010213",
    "Private_Nonfarm_Employment_2013" = "BZA110213",
    "Private_Nonfarm_Employment_pct_Change_2012-2013" = "BZA115213",
    "NonEmployer_Establishments_2013" = "NES010213",
    "Total_Number_Firms_2007" = "SBO001207",
    "Black_Owned_Firms_pct_2007" = "SBO315207",
    "American_Indian_Owned_Firms_pct_2007" = "SBO115207",
    "Asian_Owned_Firms_pct_2007" = "SBO215207",
    "Pacific_Islander_Owned_Firms_pct_2007" = "SBO515207",
    "Hispanic_Owned_Firms_pct_2007" = "SBO415207",
    "Women_Owned_Firms_pct_2007" = "SBO015207",
    "Manufacturers_Shipments_2007" = "MAN450207",
    "Merchant_Wholesaler_Sales_2007" = "WTN220207",
    "Retail_Sales_2007" = "RTN130207",
    "Retail_Sales_per_Capita_2007" = "RTN131207",
    "Accommodation_Food_Services_Sales_2007" = "AFN120207",
    "Building_Permits_2014" = "BPS030214",
    "Land_Area_square_miles_2010" = "LND110210",
    "Population_square_mile_2010" = "POP060210" )

head(df)

"""Rename columns"""

#lowercase and remove whitespace
df <- df %>% rename_all(tolower)

#name check
names(df)

#drop area_name column
df <- df %>% select(-c(area_name , state_abbreviation.y ))

df <- df %>%
  rename(state_abbreviation = state_abbreviation.x)

"""Check df shape"""

#check the shape of df
nrow(df)
ncol(df)

#check how many NAs are in the dataset
df %>%
  summarise(across(everything(), ~ sum(is.na(.))))

"""Investigate FIPS Column"""

#drop na's in fips

df <- df %>% drop_na()

#check again the shape of df
nrow(df)
ncol(df)

df <- df %>%
  mutate(fips = as.integer(fips))

"""# Data Visualizations

## Prep data to visualize vote counts & party winners
"""

head(df)

#group df by state, state_abbreviation, county, fips, party

df_grouped <- df %>%
  group_by(state, state_abbreviation , county , fips , party)

#count total votes by groups
df_grouped <- df_grouped %>%
  summarise(
    votes = sum(votes, na.rm = TRUE),
    fraction_votes = sum(fraction_votes, na.rm = TRUE),
    .groups = "drop"
  )

#pivot from long format to wide format
df_pivoted <- df_grouped %>%
  pivot_wider(
    names_from = party,
    values_from = c(votes, fraction_votes),
    names_sep = "_"

  )

head(df_pivoted)

head(df)

#left join the pivoted_df to the original df

new_df <- df %>%
left_join(df_pivoted , by = c('state', 'state_abbreviation', 'fips', 'county'))

head(new_df,20)

#create new column for overall county (party) winner
new_df <- new_df %>%
  mutate(winner = if_else(votes_Republican > votes_Democrat, "Republican", "Democrat"))

head(new_df)

"""Final Check for NA's"""

#double-check again NA's
colSums(is.na(new_df)) / nrow(new_df) * 100

#check the shape
ncol(new_df)
nrow(new_df)

#remove NA's again
new_df <- na.omit(new_df)

#re-check the shape
ncol(new_df)
nrow(new_df)

"""## Data Visualizations"""

head(new_df)

"""Population Density"""

# create summary
new_df_med.pop_summary <- new_df %>%
  group_by(winner) %>%
  summarise(median_pop = median(population_2014_estimate, na.rm = TRUE))

# plot bar chart
ggplot(new_df_med.pop_summary, aes(x = winner, y = median_pop, fill = winner)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("Democrat" = "navy", "Republican" = "red")) +
  labs(title = "Median Population in Democrat vs. Republican-leaning Counties",
       x = "County Winner", y = "Median Population") +
  theme_classic()

"""Economic Activity"""

# condense sales-related columns to one total sales column
new_df <- new_df %>%
  mutate(sales_total = accommodation_food_services_sales_2007 +
                      retail_sales_2007 +
                      retail_sales_per_capita_2007 +
                      merchant_wholesaler_sales_2007)

# Plot total sales bar chart
new_df %>%
  group_by(winner) %>%
  summarise(avg_sales = mean(sales_total, na.rm = TRUE)) %>%
  ggplot(aes(x = winner, y = avg_sales, fill = winner)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("Democrat" = "navy", "Republican" = "red")) +
  labs(title = "Average Total Sales in Democrat vs. Republican-leaning Counties",
       x = "County Winner", y = "Average Total Sales") +
  theme_classic()

"""Household Residents & Age Categories"""

# summarize age-related columns by winning party
age_summary <- new_df %>%
  group_by(winner) %>%
  summarise(
    Under_5 = mean(under_5_pct_2014, na.rm = TRUE),
    Under_18 = mean(under_18_pct_2014, na.rm = TRUE),
    Above_65 = mean(above_65_pct_2014, na.rm = TRUE)
  ) %>%
  pivot_longer(
    cols = c(Under_5, Under_18, Above_65),
    names_to = "Age_Group",
    values_to = "Mean_Percent"
  )
# Create the plot
ggplot(age_summary, aes(x = Age_Group, y = Mean_Percent, fill = winner)) +
  geom_col(position = "dodge") +
  labs(
    title = "How Do Household Age Groups Change Voting?",
    x = "Age Group",
    y = "Mean % of Population"
  ) +
  scale_fill_manual(values = c("Democrat" = "navy", "Republican" = "red")) +
  theme_classic()